export { FeatureLayout } from "./feature-layout"
export type { FeatureLayoutProps } from "./feature-layout"
export { FeatureHeader } from "./feature-header"
export type { FeatureHeaderProps, FeatureHeaderButton } from "./feature-header"
export { FeatureContent } from "./feature-content"
export type { FeatureContentProps } from "./feature-content"
export { Header } from "./Header"
export { Footer } from "./Footer"
